[book]
authors = ["'Acheul'"]
language = "en"
multilingual = false
src = "src"
title = "stats"

[build]
build-dir = "docs"

[output.html]
theme = "theme"
no-section-label = true
git-repository-url = "https://github.com/acheul"
git-repository-icon = "fa-github"
mathjax-support = true

[output.html.print]
enable = false

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 10       # the depth to start folding

[preprocessor.collector]
input_type = "toml"
# marker = "collect"
# save_path = "collect.json"
# add_title = true

[preprocessor.tagger]
# marker = "tags"
# tag2posts_path = "tag2posts.json"
# post2tags_path = "post2tags.json"
# split = ";" # ","

[preprocessor.tocjs]
# save_dir = "lib"
# theme_dir = "theme"
# block_marker_id = "tock"
# wing_marker_id = "tocw"